version: '3.8'

services:
  chatbot_api:
    build:
      context: ./chatbot_api
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    volumes:
      - ./chatbot_api/src:/app/src
    networks:
      - chatbot_network
  chatbot_frontend:
    build:
      context: ./chatbot_frontend
    env_file:
      - .env
    depends_on:
      - chatbot_api
    ports:
      - "8501:8501"
    volumes:
      - ./chatbot_frontend/src:/app/src
    networks:
      - chatbot_network
networks:
  chatbot_network:
    driver: bridge